### PR TITLE
Change #logo for StWelcomeBrowser to answer an ImageMorph with the FormSet for the icon

### PR DESCRIPTION
**Pull request by Rinzwind**
This pull request changes #logo for StWelcomeBrowser to answer an ImageMorph with the FormSet for the icon.

This requires [pharo-icon-packs pull request #11](https://github.com/pharo-project/pharo-icon-packs/pull/11) to be merged first.

### CODE REVIEW

**Review by jecisc — APPROVED** [review]

**Comment by Rinzwind** [comment]
@jecisc Thanks! Could you merge [pharo-icon-packs pull request #11](https://github.com/pharo-project/pharo-icon-packs/pull/11) as well? Otherwise the logo will be too small when using canvas scale 2 due to the FormMapping in ScalingCanvas mapping it to a Form with extent 256@256 instead of 512@512. You may also want to merge [pharo-icon-packs pull request #10](https://github.com/pharo-project/pharo-icon-packs/pull/10).

**Comment by jecisc** [comment]
I don't have the write access in this project :(

**Comment by Rinzwind** [comment]
@tesonep @estebanlm: Could either of you merge pharo-icon-packs pull requests [#10](https://github.com/pharo-project/pharo-icon-packs/pull/10) and [#11](https://github.com/pharo-project/pharo-icon-packs/pull/11)? Looking at closed pull requests in that repository, you two do have write access.

**Comment by Rinzwind** [comment]
@jecisc: Did you maybe get write access now? The [pharo-icon-packs pull request](https://github.com/pharo-project/pharo-icon-packs/pull/11) still needs to be merged to fix the logo in the Welcome Browser being too small when using world renderer canvas scale factor 2 (see screenshot below using Pharo 12 build 1504).

<p align="center">

<p>

**Comment by jecisc** [comment]
Sorry but I'm in holiday :( I do some review sometimes but I did not see the others to ask accesses.
Also with P12 been released I don't know if we should merge those in P12 branch

**Comment by Rinzwind** [comment]
Ah OK! @estebanlm: Could you merge [pharo-icon-packs pull request #11](https://github.com/pharo-project/pharo-icon-packs/pull/11) then? And maybe also [#10](https://github.com/pharo-project/pharo-icon-packs/pull/10) and [#12](https://github.com/pharo-project/pharo-icon-packs/pull/12)?

**Pull request merged**
